config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#home'

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  namespace :host do
    resources :listings
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/listing.rb
# == Schema Information
#
# Table name: listings
#
#  id            :bigint           not null, primary key
#  host_id       :bigint           not null
#  title         :string           not null
#  about         :text
#  max_guests    :integer          default(1)
#  address_line1 :string
#  address_line2 :string
#  city          :string
#  state         :string
#  postal_code   :string
#  country       :string
#  lat           :decimal(10, 6)
#  long          :decimal(10, 6)
#  status        :integer          default(0)
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#
class Listing < ApplicationRecord
  belongs_to :host, class_name: 'User'

  validates :title, presence: true
  validates :max_guests, numericality: { greater_than: 0, less_than: 101 }

  enum status: %i[draft published archived]
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :bigint           not null, primary key
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#  confirmation_token     :string
#  confirmed_at           :datetime
#  confirmation_sent_at   :datetime
#  unconfirmed_email      :string
#  failed_attempts        :integer          default(0), not null
#  unlock_token           :string
#  locked_at              :datetime
#  name                   :string
#  provider               :string
#  uid                    :string
#
class User < ApplicationRecord
  has_many :listings, foreign_key: :host_id

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable, :lockable, :timeoutable, :trackable,
         :omniauthable, omniauth_providers: [:google]

  def self.from_omniauth(access_token)
    where(provider: access_token.provider, uid: access_token.uid).first_or_create do |user|
      user.name = access_token.info.name
      user.email = access_token.info.email
      user.password = Devise.friendly_token[0, 20]

      user.skip_confirmation!
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/host/listings_controller.rb
class Host::ListingsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_listing, only: %i[show edit update destroy]

  def index
    @listings = current_user.listings.order(:id)
  end

  def new
    @listing = Listing.new
  end

  def create
    @listing = current_user.listings.new(listing_create_params)

    if @listing.save
      redirect_to host_listings_path(@listing)
    else
      flash.now[:errors] = @listing.errors.full_messages
      render :new
    end
  end

  def edit; end

  def update
    if @listing.update(listing_update_params)
      redirect_to host_listings_path(@listing)
    else
      flash.now[:errors] = @listing.errors.full_messages
      render :edit
    end
  end

  def show; end

  def destroy
    @listing.update(status: :archived)

    redirect_to host_listings_path
  end

  private

  def find_listing
    @listing = current_user.listings.find_by(id: params[:id])
  end

  def listing_create_params
    params.require(:listing).permit(
      :title,
      :about,
      :max_guests,
      :address_line1,
      :address_line2,
      :city,
      :state,
      :postal_code,
      :country
    )
  end

  def listing_update_params
    params.require(:listing).permit(
      :title,
      :about,
      :max_guests
    )
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google
    @user = User.from_omniauth(request.env['omniauth.auth'])

    if @user.persisted?
      flash[:notice] = I18n.t 'devise.omniauth_callbacks.success', kind: 'Google'
      sign_in_and_redirect @user, event: :authentication
    else
      session['devise.google_data'] = request.env['omniauth.auth'].except('extra') # Removing extra as it can overflow some session stores
      redirect_to new_user_registration_url, alert: @user.errors.full_messages.join("\n")
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/host/listings_helper.rb
module Host::ListingsHelper
  def listing_fields
    {
      title:         'text',
      about:         'textarea',
      max_guests:    'number',
      address_line1: 'text',
      address_line2: 'text',
      city:          'text',
      state:         'text',
      postal_code:   'text',
      country:       'text'
    }
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users/omniauth_callbacks_helper.rb
module Users::OmniauthCallbacksHelper
end

app/views/host/listings/edit.html.erb
<h1><%= @listing.title %></h1>

<form action="<%= host_listing_path(@listing) %>" method="post">
  <input type="hidden" name="authenticity_token" value="9JaubNOnBLl1Hh_h5dnLiV5sSUXKCkmVAgkYxs5Ysh8gIMfzaN8jwpu2cxws8moTT7KqbyLIH_kN7NhpU2DGbg">
  <input type="hidden" name="_method" value="PUT">

  <div class="field">
    <label for="title">Title</label>
    <br>
    <input type="text" name="listing[title]" id="title" value="<%= @listing.title %>">
  </div>

  <br>
  <div class="field">
    <label for="about">About</label>
    <br>
    <textarea name="listing[about]" id="about" cols="30" rows="10"><%= @listing.about %></textarea>
  </div>

  <br>
  <div class="field">
    <label for="max_guests">Max guests</label>
    <br>
    <input type="text" name="listing[max_guests]" id="max_guests" value="<%= @listing.max_guests %>">
  </div>

  <br>
  <button type="submit">Submit</button>
</form>

app/views/host/listings/index.html.erb
<h1>Host::Listings#index</h1>
<p>Find me in app/views/host/listings/index.html.erb</p>

<%= link_to 'New listing', new_host_listing_path %>

<table>
  <thead>
    <tr>
      <% listing_fields.keys.each do |field| %>
        <th><%= field %></th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% @listings.each do |listing| %>
      <tr>
        <% listing_fields.keys.each do |field| %>
          <td><%= listing[field] %></td>
        <% end %>

        <td>
          <%= link_to 'Show', host_listing_path(listing) %>
          <%= link_to 'Edit', edit_host_listing_path(listing) %>
          <%= link_to 'Remove', host_listing_path(listing), method: :delete, data: { confirm: 'Are you sure?' }  %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/host/listings/new.html.erb
<h1>New listing</h1>

<form action="/host/listings" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <div class="field">
    <label for="title">Title</label>
    <br>
    <input type="text" name="listing[title]" id="title">
  </div>

  <br>
  <div class="field">
    <label for="about">About</label>
    <br>
    <textarea name="listing[about]" id="about" cols="30" rows="10"></textarea>
  </div>
  
  <br>
  <div class="field address" data-controller="address">
    <label for="address">Address</label>
    <br>
    <input type="text" name="listing[address]" id="address" autocomplete="off">
  </div>

  <br>
  <div class="field">
    <label for="max_guests">Max guests</label>
    <br>
    <input type="text" name="listing[max_guests]" id="max_guests">
  </div>

  <br>
  <button type="submit">Submit</button>
</form>

app/views/host/listings/show.html.erb
<h1><%= @listing.title %></h1>

<%= button_to 'Edit', edit_host_listing_path(@listing), method: :get %>

<pre><%= JSON.pretty_generate(@listing.as_json) %></pre>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Clearbnb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if user_signed_in? %>
      <%= button_to 'Log out', destroy_user_session_path, method: :delete %>
    <% end %>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>

app/views/static_pages/home.html.erb
<h1>StaticPages#home</h1>
<p>Find me in app/views/static_pages/home.html.erb</p>